library(testthat)
library(microdadosBrasil)
library(RCurl)
context("Downloading source data")

#folder <- "inst/extdata"
folder <- "../../inst/extdata/"

# CAGED -------------------------------------------------------------------

test_that("Urls for CAGED are working", {

  path <- file.path(folder, "CAGED_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period=="2007-01m"])
  expect_working_link(r$download_path[r$period=="2007-02m"])
  expect_working_link(r$download_path[r$period=="2007-03m"])
  expect_working_link(r$download_path[r$period=="2007-04m"])
  expect_working_link(r$download_path[r$period=="2007-05m"])
  expect_working_link(r$download_path[r$period=="2007-06m"])
  expect_working_link(r$download_path[r$period=="2007-07m"])
  expect_working_link(r$download_path[r$period=="2007-08m"])
  expect_working_link(r$download_path[r$period=="2007-09m"])
  expect_working_link(r$download_path[r$period=="2007-10m"])
  expect_working_link(r$download_path[r$period=="2007-11m"])
  expect_working_link(r$download_path[r$period=="2007-12m"])
  expect_working_link(r$download_path[r$period=="2008-01m"])
  expect_working_link(r$download_path[r$period=="2008-02m"])
  expect_working_link(r$download_path[r$period=="2008-03m"])
  expect_working_link(r$download_path[r$period=="2008-04m"])
  expect_working_link(r$download_path[r$period=="2008-05m"])
  expect_working_link(r$download_path[r$period=="2008-06m"])
  expect_working_link(r$download_path[r$period=="2008-07m"])
  expect_working_link(r$download_path[r$period=="2008-08m"])
  expect_working_link(r$download_path[r$period=="2008-09m"])
  expect_working_link(r$download_path[r$period=="2008-10m"])
  expect_working_link(r$download_path[r$period=="2008-11m"])
  expect_working_link(r$download_path[r$period=="2008-12m"])
  expect_working_link(r$download_path[r$period=="2009-01m"])
  expect_working_link(r$download_path[r$period=="2009-02m"])
  expect_working_link(r$download_path[r$period=="2009-03m"])
  expect_working_link(r$download_path[r$period=="2009-04m"])
  expect_working_link(r$download_path[r$period=="2009-05m"])
  expect_working_link(r$download_path[r$period=="2009-06m"])
  expect_working_link(r$download_path[r$period=="2009-07m"])
  expect_working_link(r$download_path[r$period=="2009-08m"])
  expect_working_link(r$download_path[r$period=="2009-09m"])
  expect_working_link(r$download_path[r$period=="2009-10m"])
  expect_working_link(r$download_path[r$period=="2009-11m"])
  expect_working_link(r$download_path[r$period=="2009-12m"])
  expect_working_link(r$download_path[r$period=="2010-01m"])
  expect_working_link(r$download_path[r$period=="2010-02m"])
  expect_working_link(r$download_path[r$period=="2010-03m"])
  expect_working_link(r$download_path[r$period=="2010-04m"])
  expect_working_link(r$download_path[r$period=="2010-05m"])
  expect_working_link(r$download_path[r$period=="2010-06m"])
  expect_working_link(r$download_path[r$period=="2010-07m"])
  expect_working_link(r$download_path[r$period=="2010-08m"])
  expect_working_link(r$download_path[r$period=="2010-09m"])
  expect_working_link(r$download_path[r$period=="2010-10m"])
  expect_working_link(r$download_path[r$period=="2010-11m"])
  expect_working_link(r$download_path[r$period=="2010-12m"])
  expect_working_link(r$download_path[r$period=="2011-01m"])
  expect_working_link(r$download_path[r$period=="2011-02m"])
  expect_working_link(r$download_path[r$period=="2011-03m"])
  expect_working_link(r$download_path[r$period=="2011-04m"])
  expect_working_link(r$download_path[r$period=="2011-05m"])
  expect_working_link(r$download_path[r$period=="2011-06m"])
  expect_working_link(r$download_path[r$period=="2011-07m"])
  expect_working_link(r$download_path[r$period=="2011-08m"])
  expect_working_link(r$download_path[r$period=="2011-09m"])
  expect_working_link(r$download_path[r$period=="2011-10m"])
  expect_working_link(r$download_path[r$period=="2011-11m"])
  expect_working_link(r$download_path[r$period=="2011-12m"])
  expect_working_link(r$download_path[r$period=="2012-01m"])
  expect_working_link(r$download_path[r$period=="2012-02m"])
  expect_working_link(r$download_path[r$period=="2012-03m"])
  expect_working_link(r$download_path[r$period=="2012-04m"])
  expect_working_link(r$download_path[r$period=="2012-05m"])
  expect_working_link(r$download_path[r$period=="2012-06m"])
  expect_working_link(r$download_path[r$period=="2012-07m"])
  expect_working_link(r$download_path[r$period=="2012-08m"])
  expect_working_link(r$download_path[r$period=="2012-09m"])
  expect_working_link(r$download_path[r$period=="2012-10m"])
  expect_working_link(r$download_path[r$period=="2012-11m"])
  expect_working_link(r$download_path[r$period=="2012-12m"])
  expect_working_link(r$download_path[r$period=="2013-01m"])
  expect_working_link(r$download_path[r$period=="2013-02m"])
  expect_working_link(r$download_path[r$period=="2013-03m"])
  expect_working_link(r$download_path[r$period=="2013-04m"])
  expect_working_link(r$download_path[r$period=="2013-05m"])
  expect_working_link(r$download_path[r$period=="2013-06m"])
  expect_working_link(r$download_path[r$period=="2013-07m"])
  expect_working_link(r$download_path[r$period=="2013-08m"])
  expect_working_link(r$download_path[r$period=="2013-09m"])
  expect_working_link(r$download_path[r$period=="2013-10m"])
  expect_working_link(r$download_path[r$period=="2013-11m"])
  expect_working_link(r$download_path[r$period=="2013-12m"])
  expect_working_link(r$download_path[r$period=="2014-01m"])
  expect_working_link(r$download_path[r$period=="2014-02m"])
  expect_working_link(r$download_path[r$period=="2014-03m"])
  expect_working_link(r$download_path[r$period=="2014-04m"])
  expect_working_link(r$download_path[r$period=="2014-05m"])
  expect_working_link(r$download_path[r$period=="2014-06m"])
  expect_working_link(r$download_path[r$period=="2014-07m"])
  expect_working_link(r$download_path[r$period=="2014-08m"])
  expect_working_link(r$download_path[r$period=="2014-09m"])
  expect_working_link(r$download_path[r$period=="2014-10m"])
  expect_working_link(r$download_path[r$period=="2014-11m"])
  expect_working_link(r$download_path[r$period=="2014-12m"])
  expect_working_link(r$download_path[r$period=="2015-01m"])
  expect_working_link(r$download_path[r$period=="2015-02m"])
  expect_working_link(r$download_path[r$period=="2015-03m"])
  expect_working_link(r$download_path[r$period=="2015-04m"])
  expect_working_link(r$download_path[r$period=="2015-05m"])
  expect_working_link(r$download_path[r$period=="2015-06m"])
  expect_working_link(r$download_path[r$period=="2015-07m"])
  expect_working_link(r$download_path[r$period=="2015-08m"])
  expect_working_link(r$download_path[r$period=="2015-09m"])
  expect_working_link(r$download_path[r$period=="2015-10m"])
  expect_working_link(r$download_path[r$period=="2015-11m"])
  expect_working_link(r$download_path[r$period=="2015-12m"])
  expect_working_link(r$download_path[r$period=="2016-01m"])
  expect_working_link(r$download_path[r$period=="2016-02m"])
  expect_working_link(r$download_path[r$period=="2016-03m"])
  expect_working_link(r$download_path[r$period=="2016-04m"])
  expect_working_link(r$download_path[r$period=="2016-05m"])
  expect_working_link(r$download_path[r$period=="2016-06m"])
  expect_working_link(r$download_path[r$period=="2016-07m"])
  expect_working_link(r$download_path[r$period=="2016-08m"])
  expect_working_link(r$download_path[r$period=="2016-09m"])
  expect_working_link(r$download_path[r$period=="2016-10m"])
  expect_working_link(r$download_path[r$period=="2016-11m"])
  expect_working_link(r$download_path[r$period=="2016-12m"])
  expect_working_link(r$download_path[r$period=="2017-01m"])
  expect_working_link(r$download_path[r$period=="2017-02m"])
  expect_working_link(r$download_path[r$period=="2017-03m"])
  expect_working_link(r$download_path[r$period=="2017-04m"])
  expect_working_link(r$download_path[r$period=="2017-05m"])
  expect_working_link(r$download_path[r$period=="2017-06m"])
  expect_working_link(r$download_path[r$period=="2017-07m"])
  expect_working_link(r$download_path[r$period=="2017-08m"])
  expect_working_link(r$download_path[r$period=="2017-09m"])
  expect_working_link(r$download_path[r$period=="2017-10m"])
  expect_working_link(r$download_path[r$period=="2017-11m"])
  expect_working_link(r$download_path[r$period=="2017-12m"])

})


# CENSO -------------------------------------------------------------------

test_that("Urls for Censo Demográfico are working", {

  path <- file.path(folder, "CENSO_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2000])

})

# CensoEducacaoSuperior ---------------------------------------------------

test_that("Urls for Censo Educação Superior are working", {

  path <- file.path(folder, "CensoEducacaoSuperior_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==1995])
  expect_working_link(r$download_path[r$period==1996])
  expect_working_link(r$download_path[r$period==1997])
  expect_working_link(r$download_path[r$period==1998])
  expect_working_link(r$download_path[r$period==1999])
  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2001])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==2003])
  expect_working_link(r$download_path[r$period==2004])
  expect_working_link(r$download_path[r$period==2005])
  expect_working_link(r$download_path[r$period==2006])
  expect_working_link(r$download_path[r$period==2007])
  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2009])
  expect_working_link(r$download_path[r$period==2010])
  expect_working_link(r$download_path[r$period==2011])
  expect_working_link(r$download_path[r$period==2012])
  expect_working_link(r$download_path[r$period==2013])
  expect_working_link(r$download_path[r$period==2014])
  expect_working_link(r$download_path[r$period==2015])
  expect_working_link(r$download_path[r$period==2016])

})

# Censo Escolar -----------------------------------------------------------

test_that("Urls for Censo Escolar are working", {

  path <- file.path(folder, "CensoEscolar_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==1995])
  expect_working_link(r$download_path[r$period==1996])
  expect_working_link(r$download_path[r$period==1997])
  expect_working_link(r$download_path[r$period==1998])
  expect_working_link(r$download_path[r$period==1999])
  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2001])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==2003])
  expect_working_link(r$download_path[r$period==2004])
  expect_working_link(r$download_path[r$period==2005])
  expect_working_link(r$download_path[r$period==2006])
  expect_working_link(r$download_path[r$period==2007])
  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2009])
  expect_working_link(r$download_path[r$period==2010])
  expect_working_link(r$download_path[r$period==2011])
  expect_working_link(r$download_path[r$period==2012])
  expect_working_link(r$download_path[r$period==2013])
  expect_working_link(r$download_path[r$period==2014])
  expect_working_link(r$download_path[r$period==2015])
  expect_working_link(r$download_path[r$period==2016])
  expect_working_link(r$download_path[r$period==2017])

})

# ENEM --------------------------------------------------------------------

test_that("Urls for ENEM are working", {

  path <- file.path(folder, "ENEM_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==1998])
  expect_working_link(r$download_path[r$period==1999])
  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2001])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==2003])
  expect_working_link(r$download_path[r$period==2004])
  expect_working_link(r$download_path[r$period==2005])
  expect_working_link(r$download_path[r$period==2006])
  expect_working_link(r$download_path[r$period==2007])
  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2009])
  expect_working_link(r$download_path[r$period==2010])
  expect_working_link(r$download_path[r$period==2011])
  expect_working_link(r$download_path[r$period==2012])
  expect_working_link(r$download_path[r$period==2013])
  expect_working_link(r$download_path[r$period==2014])
  expect_working_link(r$download_path[r$period==2015])
  expect_working_link(r$download_path[r$period==2016])

})

# PME ---------------------------------------------------------------------

test_that("Urls for PME are working", {

  path <- file.path(folder, "PME_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period=='2002-01m'])
  expect_working_link(r$download_path[r$period=='2002-02m'])
  expect_working_link(r$download_path[r$period=='2002-03m'])
  expect_working_link(r$download_path[r$period=='2002-04m'])
  expect_working_link(r$download_path[r$period=='2002-05m'])
  expect_working_link(r$download_path[r$period=='2002-06m'])
  expect_working_link(r$download_path[r$period=='2002-07m'])
  expect_working_link(r$download_path[r$period=='2002-08m'])
  expect_working_link(r$download_path[r$period=='2002-09m'])
  expect_working_link(r$download_path[r$period=='2002-10m'])
  expect_working_link(r$download_path[r$period=='2002-11m'])
  expect_working_link(r$download_path[r$period=='2002-12m'])
  expect_working_link(r$download_path[r$period=='2003-01m'])
  expect_working_link(r$download_path[r$period=='2003-02m'])
  expect_working_link(r$download_path[r$period=='2003-03m'])
  expect_working_link(r$download_path[r$period=='2003-04m'])
  expect_working_link(r$download_path[r$period=='2003-05m'])
  expect_working_link(r$download_path[r$period=='2003-06m'])
  expect_working_link(r$download_path[r$period=='2003-07m'])
  expect_working_link(r$download_path[r$period=='2003-08m'])
  expect_working_link(r$download_path[r$period=='2003-09m'])
  expect_working_link(r$download_path[r$period=='2003-10m'])
  expect_working_link(r$download_path[r$period=='2003-11m'])
  expect_working_link(r$download_path[r$period=='2003-12m'])
  expect_working_link(r$download_path[r$period=='2004-01m'])
  expect_working_link(r$download_path[r$period=='2004-02m'])
  expect_working_link(r$download_path[r$period=='2004-03m'])
  expect_working_link(r$download_path[r$period=='2004-04m'])
  expect_working_link(r$download_path[r$period=='2004-05m'])
  expect_working_link(r$download_path[r$period=='2004-06m'])
  expect_working_link(r$download_path[r$period=='2004-07m'])
  expect_working_link(r$download_path[r$period=='2004-08m'])
  expect_working_link(r$download_path[r$period=='2004-09m'])
  expect_working_link(r$download_path[r$period=='2004-10m'])
  expect_working_link(r$download_path[r$period=='2004-11m'])
  expect_working_link(r$download_path[r$period=='2004-12m'])
  expect_working_link(r$download_path[r$period=='2005-01m'])
  expect_working_link(r$download_path[r$period=='2005-02m'])
  expect_working_link(r$download_path[r$period=='2005-03m'])
  expect_working_link(r$download_path[r$period=='2005-04m'])
  expect_working_link(r$download_path[r$period=='2005-05m'])
  expect_working_link(r$download_path[r$period=='2005-06m'])
  expect_working_link(r$download_path[r$period=='2005-07m'])
  expect_working_link(r$download_path[r$period=='2005-08m'])
  expect_working_link(r$download_path[r$period=='2005-09m'])
  expect_working_link(r$download_path[r$period=='2005-10m'])
  expect_working_link(r$download_path[r$period=='2005-11m'])
  expect_working_link(r$download_path[r$period=='2005-12m'])
  expect_working_link(r$download_path[r$period=='2006-01m'])
  expect_working_link(r$download_path[r$period=='2006-02m'])
  expect_working_link(r$download_path[r$period=='2006-03m'])
  expect_working_link(r$download_path[r$period=='2006-04m'])
  expect_working_link(r$download_path[r$period=='2006-05m'])
  expect_working_link(r$download_path[r$period=='2006-06m'])
  expect_working_link(r$download_path[r$period=='2006-07m'])
  expect_working_link(r$download_path[r$period=='2006-08m'])
  expect_working_link(r$download_path[r$period=='2006-09m'])
  expect_working_link(r$download_path[r$period=='2006-10m'])
  expect_working_link(r$download_path[r$period=='2006-11m'])
  expect_working_link(r$download_path[r$period=='2006-12m'])
  expect_working_link(r$download_path[r$period=='2007-01m'])
  expect_working_link(r$download_path[r$period=='2007-02m'])
  expect_working_link(r$download_path[r$period=='2007-03m'])
  expect_working_link(r$download_path[r$period=='2007-04m'])
  expect_working_link(r$download_path[r$period=='2007-05m'])
  expect_working_link(r$download_path[r$period=='2007-06m'])
  expect_working_link(r$download_path[r$period=='2007-07m'])
  expect_working_link(r$download_path[r$period=='2007-08m'])
  expect_working_link(r$download_path[r$period=='2007-09m'])
  expect_working_link(r$download_path[r$period=='2007-10m'])
  expect_working_link(r$download_path[r$period=='2007-11m'])
  expect_working_link(r$download_path[r$period=='2007-12m'])
  expect_working_link(r$download_path[r$period=='2008-01m'])
  expect_working_link(r$download_path[r$period=='2008-02m'])
  expect_working_link(r$download_path[r$period=='2008-03m'])
  expect_working_link(r$download_path[r$period=='2008-04m'])
  expect_working_link(r$download_path[r$period=='2008-05m'])
  expect_working_link(r$download_path[r$period=='2008-06m'])
  expect_working_link(r$download_path[r$period=='2008-07m'])
  expect_working_link(r$download_path[r$period=='2008-08m'])
  expect_working_link(r$download_path[r$period=='2008-09m'])
  expect_working_link(r$download_path[r$period=='2008-10m'])
  expect_working_link(r$download_path[r$period=='2008-11m'])
  expect_working_link(r$download_path[r$period=='2008-12m'])
  expect_working_link(r$download_path[r$period=='2009-01m'])
  expect_working_link(r$download_path[r$period=='2009-02m'])
  expect_working_link(r$download_path[r$period=='2009-03m'])
  expect_working_link(r$download_path[r$period=='2009-04m'])
  expect_working_link(r$download_path[r$period=='2009-05m'])
  expect_working_link(r$download_path[r$period=='2009-06m'])
  expect_working_link(r$download_path[r$period=='2009-07m'])
  expect_working_link(r$download_path[r$period=='2009-08m'])
  expect_working_link(r$download_path[r$period=='2009-09m'])
  expect_working_link(r$download_path[r$period=='2009-10m'])
  expect_working_link(r$download_path[r$period=='2009-11m'])
  expect_working_link(r$download_path[r$period=='2009-12m'])
  expect_working_link(r$download_path[r$period=='2010-01m'])
  expect_working_link(r$download_path[r$period=='2010-02m'])
  expect_working_link(r$download_path[r$period=='2010-03m'])
  expect_working_link(r$download_path[r$period=='2010-04m'])
  expect_working_link(r$download_path[r$period=='2010-05m'])
  expect_working_link(r$download_path[r$period=='2010-06m'])
  expect_working_link(r$download_path[r$period=='2010-07m'])
  expect_working_link(r$download_path[r$period=='2010-08m'])
  expect_working_link(r$download_path[r$period=='2010-09m'])
  expect_working_link(r$download_path[r$period=='2010-10m'])
  expect_working_link(r$download_path[r$period=='2010-11m'])
  expect_working_link(r$download_path[r$period=='2010-12m'])
  expect_working_link(r$download_path[r$period=='2011-01m'])
  expect_working_link(r$download_path[r$period=='2011-02m'])
  expect_working_link(r$download_path[r$period=='2011-03m'])
  expect_working_link(r$download_path[r$period=='2011-04m'])
  expect_working_link(r$download_path[r$period=='2011-05m'])
  expect_working_link(r$download_path[r$period=='2011-06m'])
  expect_working_link(r$download_path[r$period=='2011-07m'])
  expect_working_link(r$download_path[r$period=='2011-08m'])
  expect_working_link(r$download_path[r$period=='2011-09m'])
  expect_working_link(r$download_path[r$period=='2011-10m'])
  expect_working_link(r$download_path[r$period=='2011-11m'])
  expect_working_link(r$download_path[r$period=='2011-12m'])
  expect_working_link(r$download_path[r$period=='2012-01m'])
  expect_working_link(r$download_path[r$period=='2012-02m'])
  expect_working_link(r$download_path[r$period=='2012-03m'])
  expect_working_link(r$download_path[r$period=='2012-04m'])
  expect_working_link(r$download_path[r$period=='2012-05m'])
  expect_working_link(r$download_path[r$period=='2012-06m'])
  expect_working_link(r$download_path[r$period=='2012-07m'])
  expect_working_link(r$download_path[r$period=='2012-08m'])
  expect_working_link(r$download_path[r$period=='2012-09m'])
  expect_working_link(r$download_path[r$period=='2012-10m'])
  expect_working_link(r$download_path[r$period=='2012-11m'])
  expect_working_link(r$download_path[r$period=='2012-12m'])
  expect_working_link(r$download_path[r$period=='2013-01m'])
  expect_working_link(r$download_path[r$period=='2013-02m'])
  expect_working_link(r$download_path[r$period=='2013-03m'])
  expect_working_link(r$download_path[r$period=='2013-04m'])
  expect_working_link(r$download_path[r$period=='2013-05m'])
  expect_working_link(r$download_path[r$period=='2013-06m'])
  expect_working_link(r$download_path[r$period=='2013-07m'])
  expect_working_link(r$download_path[r$period=='2013-08m'])
  expect_working_link(r$download_path[r$period=='2013-09m'])
  expect_working_link(r$download_path[r$period=='2013-10m'])
  expect_working_link(r$download_path[r$period=='2013-11m'])
  expect_working_link(r$download_path[r$period=='2013-12m'])
  expect_working_link(r$download_path[r$period=='2014-01m'])
  expect_working_link(r$download_path[r$period=='2014-02m'])
  expect_working_link(r$download_path[r$period=='2014-03m'])
  expect_working_link(r$download_path[r$period=='2014-04m'])
  expect_working_link(r$download_path[r$period=='2014-05m'])
  expect_working_link(r$download_path[r$period=='2014-06m'])
  expect_working_link(r$download_path[r$period=='2014-07m'])
  expect_working_link(r$download_path[r$period=='2014-08m'])
  expect_working_link(r$download_path[r$period=='2014-09m'])
  expect_working_link(r$download_path[r$period=='2014-10m'])
  expect_working_link(r$download_path[r$period=='2014-11m'])
  expect_working_link(r$download_path[r$period=='2014-12m'])
  expect_working_link(r$download_path[r$period=='2015-01m'])
  expect_working_link(r$download_path[r$period=='2015-02m'])
  expect_working_link(r$download_path[r$period=='2015-03m'])
  expect_working_link(r$download_path[r$period=='2015-04m'])
  expect_working_link(r$download_path[r$period=='2015-05m'])
  expect_working_link(r$download_path[r$period=='2015-06m'])
  expect_working_link(r$download_path[r$period=='2015-07m'])
  expect_working_link(r$download_path[r$period=='2015-08m'])
  expect_working_link(r$download_path[r$period=='2015-09m'])
  expect_working_link(r$download_path[r$period=='2015-10m'])
  expect_working_link(r$download_path[r$period=='2015-11m'])
  expect_working_link(r$download_path[r$period=='2015-12m'])
  expect_working_link(r$download_path[r$period=='2016-01m'])
  expect_working_link(r$download_path[r$period=='2016-02m'])

})

# PNAD --------------------------------------------------------------------

test_that("Urls for PNAD are working", {

  path <- file.path(folder, "PNAD_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==1976])
  expect_working_link(r$download_path[r$period==1977])
  expect_working_link(r$download_path[r$period==1978])
  expect_working_link(r$download_path[r$period==1979])
  expect_working_link(r$download_path[r$period==1980])
  expect_working_link(r$download_path[r$period==1981])
  expect_working_link(r$download_path[r$period==1982])
  expect_working_link(r$download_path[r$period==1983])
  expect_working_link(r$download_path[r$period==1984])
  expect_working_link(r$download_path[r$period==1985])
  expect_working_link(r$download_path[r$period==1986])
  expect_working_link(r$download_path[r$period==1987])
  expect_working_link(r$download_path[r$period==1988])
  expect_working_link(r$download_path[r$period==1989])
  expect_working_link(r$download_path[r$period==1990])
  expect_working_link(r$download_path[r$period==1991])
  expect_working_link(r$download_path[r$period==1992])
  expect_working_link(r$download_path[r$period==1993])
  expect_working_link(r$download_path[r$period==1994])
  expect_working_link(r$download_path[r$period==1995])
  expect_working_link(r$download_path[r$period==1996])
  expect_working_link(r$download_path[r$period==1997])
  expect_working_link(r$download_path[r$period==1998])
  expect_working_link(r$download_path[r$period==1999])
  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2001])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==2003])
  expect_working_link(r$download_path[r$period==2004])
  expect_working_link(r$download_path[r$period==2005])
  expect_working_link(r$download_path[r$period==2006])
  expect_working_link(r$download_path[r$period==2007])
  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2009])
  expect_working_link(r$download_path[r$period==2011])
  expect_working_link(r$download_path[r$period==2012])
  expect_working_link(r$download_path[r$period==2013])
  expect_working_link(r$download_path[r$period==2014])
  expect_working_link(r$download_path[r$period==2015])

})

# PnadContinua ------------------------------------------------------------

test_that("Urls for PnadContinua are working", {

  path <- file.path(folder, "PnadContinua_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period=='2012-1q'])
  expect_working_link(r$download_path[r$period=='2012-2q'])
  expect_working_link(r$download_path[r$period=='2012-3q'])
  expect_working_link(r$download_path[r$period=='2012-4q'])
  expect_working_link(r$download_path[r$period=='2013-1q'])
  expect_working_link(r$download_path[r$period=='2013-2q'])
  expect_working_link(r$download_path[r$period=='2013-3q'])
  expect_working_link(r$download_path[r$period=='2013-4q'])
  expect_working_link(r$download_path[r$period=='2014-1q'])
  expect_working_link(r$download_path[r$period=='2014-2q'])
  expect_working_link(r$download_path[r$period=='2014-3q'])
  expect_working_link(r$download_path[r$period=='2014-4q'])
  expect_working_link(r$download_path[r$period=='2015-1q'])
  expect_working_link(r$download_path[r$period=='2015-2q'])
  expect_working_link(r$download_path[r$period=='2015-3q'])
  expect_working_link(r$download_path[r$period=='2015-4q'])
  expect_working_link(r$download_path[r$period=='2016-1q'])
  expect_working_link(r$download_path[r$period=='2016-2q'])
  expect_working_link(r$download_path[r$period=='2016-3q'])
  expect_working_link(r$download_path[r$period=='2016-4q'])
  expect_working_link(r$download_path[r$period=='2017-1q'])
  expect_working_link(r$download_path[r$period=='2017-2q'])
  expect_working_link(r$download_path[r$period=='2017-3q'])
  expect_working_link(r$download_path[r$period=='2017-4q'])
  expect_working_link(r$download_path[r$period=='2018-1q'])
  expect_working_link(r$download_path[r$period=='2018-2q'])
  expect_working_link(r$download_path[r$period=='2012-anual-1v'])
  expect_working_link(r$download_path[r$period=='2013-anual-1v'])
  expect_working_link(r$download_path[r$period=='2014-anual-1v'])
  expect_working_link(r$download_path[r$period=='2015-anual-1v'])
  expect_working_link(r$download_path[r$period=='2016-anual-1v'])
  expect_working_link(r$download_path[r$period=='2017-anual-1v'])
  expect_working_link(r$download_path[r$period=='2017-anual-5v'])

})

# PNS ---------------------------------------------------------------------

test_that("Urls for PNS are working", {

  path <- file.path(folder, "PNS_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==2013])

})

# POF ---------------------------------------------------------------------

test_that("Urls for POF are working", {

  path <- file.path(folder, "POF_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==1995])
  expect_working_link(r$download_path[r$period==1987])

})

# RAIS --------------------------------------------------------------------

test_that("Urls for RAIS are working", {

  path <- file.path(folder, "RAIS_files_metadata_harmonization.csv")

  r <- read.csv2(path, stringsAsFactors = FALSE)

  expect_working_link <- function(link) {
    eval(bquote(expect_equal(url.exists(link), TRUE)))
  }

  expect_working_link(r$download_path[r$period==1985])
  expect_working_link(r$download_path[r$period==1986])
  expect_working_link(r$download_path[r$period==1987])
  expect_working_link(r$download_path[r$period==1988])
  expect_working_link(r$download_path[r$period==1989])
  expect_working_link(r$download_path[r$period==1990])
  expect_working_link(r$download_path[r$period==1991])
  expect_working_link(r$download_path[r$period==1992])
  expect_working_link(r$download_path[r$period==1993])
  expect_working_link(r$download_path[r$period==1994])
  expect_working_link(r$download_path[r$period==1995])
  expect_working_link(r$download_path[r$period==1996])
  expect_working_link(r$download_path[r$period==1997])
  expect_working_link(r$download_path[r$period==1998])
  expect_working_link(r$download_path[r$period==1999])
  expect_working_link(r$download_path[r$period==2000])
  expect_working_link(r$download_path[r$period==2001])
  expect_working_link(r$download_path[r$period==2002])
  expect_working_link(r$download_path[r$period==2003])
  expect_working_link(r$download_path[r$period==2004])
  expect_working_link(r$download_path[r$period==2005])
  expect_working_link(r$download_path[r$period==2006])
  expect_working_link(r$download_path[r$period==2007])
  expect_working_link(r$download_path[r$period==2008])
  expect_working_link(r$download_path[r$period==2009])
  expect_working_link(r$download_path[r$period==2010])
  expect_working_link(r$download_path[r$period==2011])
  expect_working_link(r$download_path[r$period==2012])
  expect_working_link(r$download_path[r$period==2013])
  expect_working_link(r$download_path[r$period==2014])
  expect_working_link(r$download_path[r$period==2015])
  expect_working_link(r$download_path[r$period==2016])

})
